/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function concatStr(a: string, b: string): string
export interface ToolOptions {
  id: number
  name: string
}
export function getOptions(options: ToolOptions): ToolOptions
